= SpringSecurityAclModule
Arne Vandamme
3.0.0-SNAPSHOT
:toc: left
:sectanchors:
:module-version: 3.0.0-SNAPSHOT
:module-name: SpringSecurityAclModule
:module-artifact: spring-security-acl-module
:module-url: https://across.foreach.be/modules/SpringSecurityAclModule
:entity-module-url: https://across.foreach.be/modules/EntityModule

[copyright,verbatim]
--
Copyright (C) 2014-2017 +
[small]#Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.#
--

:numbered:
== General information

=== Artifact
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>com.foreach.across.modules</groupId>
			<artifactId>{module-artifact}</artifactId>
			<version>{module-version}</version>
		</dependency>
	</dependencies>
----

=== Module dependencies

.Module dependencies
|===
|Module |Type |Description

|`SpringSecurityModule`
|required
|Provides the basic security infrastructure.

|`AcrossHibernateJpaModule`
|optional
|Activates support for ACL security entities.

|`EntityModule`
|optional
|Enables the management forms for ACL security entities.

|===

=== Module settings
This module has no specific settings.

== What's new in this version?
:numbered!:
=== 3.0.0-SNAPSHOT
* SpringSecurityAclModule now uses a single `AclPermissionFactory` for the actual permission management
** custom permissions can be registered on this factory and made available for use in security expressions
* the first 10 permission positions (bit flags) are now reserved for Across internal use
** the 5 default permissions take up half of these positions
** applications or non-shared modules should create custom permissions on the positions > 10
* `AclPermission` has some helper methods for easily creating custom permissions: `create()` and `combine()`, with validation regarding the reserved bit range
* TODO: AclPermissionForm
** registry for registration
** ObjectIdentity.class.getName() attribute for custom identity resolver
** the auto generated ACL permissions management view uses several <<acl-permissions-form-message-codes,message codes>> for its labels

=== 2.0.1.RELEASE
* added support for H2 database

:numbered:
== About the SpringSecurityAclModule
The `SpringSecurityAclModule` enables Access Control Lists for managing permissions.  The core service for working
with the ACLs is the `AclSecurityService` and supports management of ACLs attached to `IdBasedEntity` instances,
seamlessly integrating with other standard modules.

ACLs define which security entities have access to a certain object or type through the use of Access Control Entries (ACE).
An ACE defines access for a single <<known-acl-permissions,acl permission>> for a certain `Sid`, which represents the security entity.
{module-name} provides an `Sid` implementation for working with `GrantedAuthority` and `SecurityPrincipal`, which are `GrantedAuthoritySid` and `SecurityPrincipalSid` respectively.
When creating an ACL, the current authentication will be set as it's owner and will be the default manager of the ACL for that object.

[#default-parent-acl]
=== Default parent ACL
The `AclSecurityService` optionally allows setting a default parent ACL (in the form of the `IdBasedEntity`
that owns the ACL).  The default parent is attached to any newly created ACL that does not have an explicit parent
specified.

=== ACL security entities
The `SpringSecurityAclModule` packs a domain model for ACL security entities.  These are abstract database entities
that serve no other purpose than attaching an ACL to them.  They optionally take another security entity as parent,
whose ACL will then also be the parent ACL.

The ACL security entity hierarchy exactly represents the backing ACL hierarchy.  ACL security entities are usually
only developer managed and by default require the *acl take ownership* permissions to manage them through the
administrative interface.

The standard `UserModule` provides a default installation of security entities, and sets the *system* security entity
for the default parent ACL.

=== Global permissions
The `SpringSecurityAclModule` defines 3 global permissions, these are available as constants in the `AclAuthorities` interface.

.Global permission overview
|===
|Permission |Description

|*acl take ownership*
|Allows the authenticated principal to take ownership of any ACL. Also the required permission to be able
to manage ACL security entities.

|*acl modify*
|Allows the authenticated principal to modify any ACL.  This includes adding and removing ACE records but
excludes changing ownership.

|*acl audit*
|Allows the authenticated principal to modify the auditing settings of an ACL.

|===

[[known-acl-permissions]]
== Known ACL permissions
The following lists the known/used ACL permissions from shared modules.

An ACL permission:

* takes a single bit position (total range is numbered from 0 to 31)
* optionally has a single character code that is used when displaying a permission pattern (eg. `\...\...\...\...\...\...\...\...\....D.WR`)
* has a unique name that can be used in expression based security (eg. `hasPermission(#object,'my-permission')`)

[discrete]
=== Reserved bit range
The first 10 bit positions are reserved for use by Across standard modules.
To avoid conflicts with this range, use `AclPermission.create()` for defining your custom permissions.

|===
|Bit position |Permission name |Code |Module

|0 |read | R |SpringSecurityAclModule
|1 |write |W |SpringSecurityAclModule
|2 |create |C |SpringSecurityAclModule
|3 |delete |D |SpringSecurityAclModule
|4 |administration |A |SpringSecurityAclModule

|===

[discrete]
=== Open bit range
The open bit range (> position 10) is meant for custom applications or modules.

=== Creating custom ACL permissions

To create your own ACL permission, simply use the AclPermission#create method, which accepts an integer definition it's bit position.
After creating your custom permissions, you register them to the AclPermissionFactory and you're set to use them in your application.

In general it's a good idea to keep your custom ACL permissions in a single location within your application.

// TODO CumulativePermission
.Registering a custom ACL permission
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@Configuration
public class MyApplicationPermissions {

    public static final AclPermission MY_CUSTOM_PERMISSION = AclPermission.create(10);

    @Autowired
    void registerPermissions(AclPermissionFactory permissionFactory){
        permissionFactory.registerPermission( MY_CUSTOM_PERMISSION, "my-custom-permission" );
    }
}
----

=== Managing ACLs

==== IdBasedEntityAclInterceptor
{module-name} provides a custom interceptor that provides a few utility methods to handle ACLs for `IdBasedEntity` types.
These are primarily used to create an ACL when an object of a certain type is created, as well as providing access to the object for the necessary security entities by defaul.

.Creating a custom Acl interceptor.
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@Component
class ProjectAclInterceptor extends IdBasedEntityAclInterceptor<Project> {
    @Override
    public boolean handles( Class<?> entityClass ) {
        return Project.class.isAssignableFrom( entityClass );
    }

    @Override
    public void afterCreate( Project entity ) {
        if ( aclSecurityService().getAcl( entity ) == null ) {
            aclSecurityService().createAcl( entity );
            // All users that have the MANAGE_USERS authority, will have the READ and WRITE permissions for the project instance.
            aclSecurityService().allow( UserAuthorities.MANAGE_USERS, entity, AclPermission.READ, AclPermission.WRITE );
        }
    }

    @Override
    public void beforeDelete( Project entity ) {
        Acl acl = aclSecurityService().getAcl( entity );
        if ( acl != null ) {
            aclSecurityService().deleteAcl( entity, true );
        }
    }
}
----

//TODO
==== AclSecurityService
//
//allow-revoke-deny-hasPermission
//
==== Defining access using AllowableActions
//
//AllowableActionsMapper

=== Configuring an ACL form

To create an ACL form through which users can manage ACL's from the back-end of the application, one has to register a form on the AclPermissionFormRegistry and add that form to the EntityConfigurationBuilder of your entity.
The ACL form allows to split up the handling of permissions in logical sections and groups.
This will not affect on how permissions are handled underlying, but offers a clearer user interface.
When creating `AclPermissionsFormSection`s, most options can be left open and sensible defaults will be generated.

.Registering an AclPermissionsForm
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
@Autowired
void registerAclPermissionsForm(AclPermissionsFormRegistry formRegistry){
    // Create a section that defines access to the object for users.
    AclPermissionsFormSection userSection = AclPermissionsForm
        .section("user") // name of the section
        .entityType(User.class) // the entity type for which access will be defined
        .permissionGroups( // define the logical grouping of permissions
            permissionGroup( "general" ) // name of the group
                // permissions that should be shown in this group
                .permissions(AclPermission.CREATE, AclPermission.READ, AclPermission.WRITE, AclPermission.DELETE)
                .build(),
            permissionsGroup("administration")
                .permissions(AclPermission.ADMINISTRATION)
                .build()
        ).build();

    // register the form under the name 'project'
    formRegistry.put("project", AclPermissionsForm.builder()
                                                  .name("project") // name of the form
                                                  .section(userSection) // registering the section on the form
                                                  .build()
    );
}
----

.Registering the form on an EntityConfigurationBuilder
[source,java,indent=0]
[subs="verbatim,quotes,attributes"]
----
public void configure(EntitiesConfigurationBuilder entities){
    entities.withType(Project.class)
            // register the 'project' AclPermissionsForm on the Project EntityConfiguration
            .attribute(AclPermissionsForm.ATTR_PROFILE_NAME, "project");
}
----

include::message-codes.adoc[]

